// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29l9gZIADAx3CWDMgX_Djd3EV93nUEo0',
    appId: '1:143120475321:web:61f276a0a441e348fee768',
    messagingSenderId: '143120475321',
    projectId: 'chat-app-fc1e1',
    authDomain: 'chat-app-fc1e1.firebaseapp.com',
    storageBucket: 'chat-app-fc1e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSHq2by6ACeg4JGDry2wAuElEGb9m6iY',
    appId: '1:143120475321:android:bf2c152ae678f396fee768',
    messagingSenderId: '143120475321',
    projectId: 'chat-app-fc1e1',
    storageBucket: 'chat-app-fc1e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPrx5VS-lOZvK3TP2Txaty_Jb9yC2mBw',
    appId: '1:143120475321:ios:923f8d068801b9cefee768',
    messagingSenderId: '143120475321',
    projectId: 'chat-app-fc1e1',
    storageBucket: 'chat-app-fc1e1.appspot.com',
    iosClientId: '143120475321-s68k4697ltad8ndunh3t1303enbhrc34.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUPrx5VS-lOZvK3TP2Txaty_Jb9yC2mBw',
    appId: '1:143120475321:ios:e07778b0f0e17e0afee768',
    messagingSenderId: '143120475321',
    projectId: 'chat-app-fc1e1',
    storageBucket: 'chat-app-fc1e1.appspot.com',
    iosClientId: '143120475321-1dv6mh86i12c543rd9vneii1k9umf765.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
